//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.Aggregation.Devices.Printer.Resources.ZPL {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Printer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Printer() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.Aggregation.Devices.Printer.Resources.ZPL.Printer", typeof(Printer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MarkingLine.
        /// </summary>
        internal static string ConfigMarkingLine {
            get {
                return ResourceManager.GetString("ConfigMarkingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Printer.
        /// </summary>
        internal static string ConfigPrinter {
            get {
                return ResourceManager.GetString("ConfigPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать этикетки выполнена за {0}.
        /// </summary>
        internal static string DbgPrintTime {
            get {
                return ResourceManager.GetString("DbgPrintTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинаем загрузку из файла {0}.
        /// </summary>
        internal static string DbgReadFile {
            get {
                return ResourceManager.GetString("DbgReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство на падключено, но нанего пытамся отправить данные..
        /// </summary>
        internal static string DeviceNull {
            get {
                return ResourceManager.GetString("DeviceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось выполнить команду..
        /// </summary>
        internal static string ErrExecutionCommand {
            get {
                return ResourceManager.GetString("ErrExecutionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет подключения к устройству.
        /// </summary>
        internal static string ErrNoConnect {
            get {
                return ResourceManager.GetString("ErrNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из файла не были прочитаны данные. Файл {0}.
        /// </summary>
        internal static string ErrorNotRead {
            get {
                return ResourceManager.GetString("ErrorNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исключение при открытии и отправке файла на принтер:{0}.
        /// </summary>
        internal static string ExepReadFile {
            get {
                return ResourceManager.GetString("ExepReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не смогли открыть соединение с принтером.
        /// </summary>
        internal static string FailTcp {
            get {
                return ResourceManager.GetString("FailTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В информации о коде не найдены данные по ключу [{0}].
        /// </summary>
        internal static string ImageNoKey {
            get {
                return ResourceManager.GetString("ImageNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл для отправки на принтер не найден. Полный путь к файлу {0}.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В буфере принтера {0} байт: {1}.
        /// </summary>
        internal static string ReadBuffer {
            get {
                return ResourceManager.GetString("ReadBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка отправки сообщения на принтер: {0}.
        /// </summary>
        internal static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинаем инициализацию устройства.
        /// </summary>
        internal static string StartInit {
            get {
                return ResourceManager.GetString("StartInit", resourceCulture);
            }
        }
    }
}
