//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.Aggregation.Devices.Printer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Printer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Printer() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.Aggregation.Devices.Printer.Resources.Printer", typeof(Printer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполнении поля {0} с индексом {1} не смогли найти значение {2}. Поле в код не добавлено.
        /// </summary>
        internal static string ErrNoGSCode {
            get {
                return ResourceManager.GetString("ErrNoGSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполнения поля {0} с индексом {1} не указано имя поле кода. Поля в код не добавлено.
        /// </summary>
        internal static string ErrNoGSName {
            get {
                return ResourceManager.GetString("ErrNoGSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполненни поля из номенклатуры с индексом {0} не смогли найти значение {1}. Поле в код не добавлено.
        /// </summary>
        internal static string ErrNoResourceCode {
            get {
                return ResourceManager.GetString("ErrNoResourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполнении поля c индексом {0} не указано имя данных. Поле в код не добавлено.
        /// </summary>
        internal static string ErrNoResourceName {
            get {
                return ResourceManager.GetString("ErrNoResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполненни поля SerialNumber с индексом {0} не смогли найти значение {1}. Поле в код не добавлено.
        /// </summary>
        internal static string ErrNoSerialCode {
            get {
                return ResourceManager.GetString("ErrNoSerialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполнения поля SerialNumber с индексом {0} не указано имя поля кода. Поле в код не добавлено.
        /// </summary>
        internal static string ErrNoSerialName {
            get {
                return ResourceManager.GetString("ErrNoSerialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не инициализировано поле шаблона кода. Создание кода не выполнено.
        /// </summary>
        internal static string ErrNoTemplate {
            get {
                return ResourceManager.GetString("ErrNoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При заполнении поля константы с индексом {0} выяснилось что в шаблоне пусто..
        /// </summary>
        internal static string WarnNoConstantChar {
            get {
                return ResourceManager.GetString("WarnNoConstantChar", resourceCulture);
            }
        }
    }
}
