//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.Aggregation.Devices.Tcp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Builder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Builder() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.Aggregation.Devices.Tcp.Resources.Builder", typeof(Builder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрываем поток для записи/чтения.
        /// </summary>
        internal static string CloseStream {
            get {
                return ResourceManager.GetString("CloseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие соединения TCP выполнено..
        /// </summary>
        internal static string ConnectSucces {
            get {
                return ResourceManager.GetString("ConnectSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не смогли открыть соединение за {0} мс..
        /// </summary>
        internal static string ConnectTimeOut {
            get {
                return ResourceManager.GetString("ConnectTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получаем поток для записи/чтения.
        /// </summary>
        internal static string CreateStream {
            get {
                return ResourceManager.GetString("CreateStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создаем клиент TCP.
        /// </summary>
        internal static string CreateTcp {
            get {
                return ResourceManager.GetString("CreateTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрываем TCP соединение.
        /// </summary>
        internal static string DisposeTcp {
            get {
                return ResourceManager.GetString("DisposeTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов потока TcpBuilder ожидал аргумента типа IConfiguration, однако прилетел тип {0}.
        /// </summary>
        internal static string ErrArg {
            get {
                return ResourceManager.GetString("ErrArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При открытии TCP соединения возникло исключение:{0}.
        /// </summary>
        internal static string ExpOpen {
            get {
                return ResourceManager.GetString("ExpOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открываем TCP соединение с IP={0}:{1}.
        /// </summary>
        internal static string OpenTcp {
            get {
                return ResourceManager.GetString("OpenTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буфер чтения сокета содержит {0} байт..
        /// </summary>
        internal static string StreamBuffer {
            get {
                return ResourceManager.GetString("StreamBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток для записи/чтения не был создан.
        /// </summary>
        internal static string StreamNotOpen {
            get {
                return ResourceManager.GetString("StreamNotOpen", resourceCulture);
            }
        }
    }
}
