//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.Aggregation.Devices.Tcp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Device {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Device() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.Aggregation.Devices.Tcp.Resources.Device", typeof(Device).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрываем поток для записи/чтения.
        /// </summary>
        internal static string CloseStream {
            get {
                return ResourceManager.GetString("CloseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаем поток для записи/чтения.
        /// </summary>
        internal static string CreateStream {
            get {
                return ResourceManager.GetString("CreateStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрываем поток для записи/чтения.
        /// </summary>
        internal static string DbgCloseStream {
            get {
                return ResourceManager.GetString("DbgCloseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрываем TCP соединение.
        /// </summary>
        internal static string DbgDisposeTcp {
            get {
                return ResourceManager.GetString("DbgDisposeTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Освобождение ресурсов устройства для IP={0}.
        /// </summary>
        internal static string DbgRelease {
            get {
                return ResourceManager.GetString("DbgRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрываем TCP соединение.
        /// </summary>
        internal static string DisposeTcp {
            get {
                return ResourceManager.GetString("DisposeTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При попытке получения строки енкодером {0} из массива байт размером {1} возникло исключение:{2}.
        /// </summary>
        internal static string ExceptErrorEncoding {
            get {
                return ResourceManager.GetString("ExceptErrorEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При попытке чтения {0} байт из буфера вознилко исключение: {1}.
        /// </summary>
        internal static string ExceptErrorRead {
            get {
                return ResourceManager.GetString("ExceptErrorRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исключение при освобождении ресурсов: {0}.
        /// </summary>
        internal static string ExceptErrorRelease {
            get {
                return ResourceManager.GetString("ExceptErrorRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При попытке запросить кол-во доступных данных возникло исключение: {0}.
        /// </summary>
        internal static string ExceptErrorTcp {
            get {
                return ResourceManager.GetString("ExceptErrorTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент не создан!.
        /// </summary>
        internal static string ExpClientIsNull {
            get {
                return ResourceManager.GetString("ExpClientIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрыв соединения, попытка {0} восстановить связь после {1} ожидания.
        /// </summary>
        internal static string ReconectTry {
            get {
                return ResourceManager.GetString("ReconectTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буфер чтения сокета содержит {0} байт..
        /// </summary>
        internal static string StreamBuffer {
            get {
                return ResourceManager.GetString("StreamBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поток для записи/чтения не был создан.
        /// </summary>
        internal static string StreamNotOpen {
            get {
                return ResourceManager.GetString("StreamNotOpen", resourceCulture);
            }
        }
    }
}
